# Generated by Django 6.0.3 on 2026-05-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('nao_iniciada', 'Nao iniciada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida')], default='nao_iniciada', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_estudo', 'Em estudo'), ('concluido', 'Concluido')], default='pendente', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='planejamento.disciplina')),
            ],
            options={
                'ordering': ['disciplina__nome', 'titulo'],
            },
        ),
    ]
