# Generated by Django 6.0.3 on 2026-05-24 20:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='titulo')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at', 'prioridade'],
            },
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='atualizada_em',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='criada_em',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='status',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ano_escolar',
            field=models.CharField(default='Nao informado', max_length=50, verbose_name='ano escolar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveIntegerField(verbose_name='carga horaria'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='nome'),
        ),
        migrations.CreateModel(
            name='ConteudoProgramatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='titulo')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
                ('unidade', models.CharField(max_length=80, verbose_name='unidade')),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(1, '1 bimestre'), (2, '2 bimestre'), (3, '3 bimestre'), (4, '4 bimestre')], verbose_name='bimestre')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluido')], default='pendente', max_length=20, verbose_name='status')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='data prevista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos_programaticos', to='planejamento.disciplina', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'Conteudo programatico',
                'verbose_name_plural': 'Conteudos programaticos',
                'ordering': ['disciplina__nome', 'bimestre', 'unidade', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='data de inicio')),
                ('data_fim', models.DateField(verbose_name='data de fim')),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluido'), ('atrasado', 'Atrasado')], default='planejado', max_length=20, verbose_name='status')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='planejamento.disciplina', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'ordering': ['data_inicio', 'disciplina__nome'],
            },
        ),
        migrations.DeleteModel(
            name='Conteudo',
        ),
    ]
