# Generated by Django 6.0.3 on 2026-05-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/fotos/', verbose_name='foto'),
        ),
    ]
