# Generated by Django 6.0.3 on 2026-05-24 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_conteudos_existentes(apps, schema_editor):
    ConteudoProgramatico = apps.get_model('planejamento', 'ConteudoProgramatico')
    status_map = {
        'pendente': 'PENDENTE',
        'em_andamento': 'EM_ANDAMENTO',
        'concluido': 'CONCLUIDO',
    }
    periodo_map = {
        1: '1_BIMESTRE',
        2: '2_BIMESTRE',
        3: '3_BIMESTRE',
        4: '4_BIMESTRE',
    }

    for conteudo in ConteudoProgramatico.objects.all():
        alterado = False

        novo_status = status_map.get(conteudo.status)
        if novo_status:
            conteudo.status = novo_status
            conteudo.concluido = novo_status == 'CONCLUIDO'
            alterado = True

        if not conteudo.tipo_periodo:
            conteudo.tipo_periodo = 'BIMESTRE'
            alterado = True

        if not conteudo.periodo:
            conteudo.periodo = periodo_map.get(conteudo.bimestre)
            alterado = True

        if alterado:
            conteudo.save()


def reverter_conteudos_existentes(apps, schema_editor):
    ConteudoProgramatico = apps.get_model('planejamento', 'ConteudoProgramatico')
    status_map = {
        'PENDENTE': 'pendente',
        'EM_ANDAMENTO': 'em_andamento',
        'CONCLUIDO': 'concluido',
        'ATRASADO': 'pendente',
    }

    for conteudo in ConteudoProgramatico.objects.all():
        conteudo.status = status_map.get(conteudo.status, conteudo.status)
        conteudo.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0004_alter_perfilusuario_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='planejamento.conteudoprogramatico', verbose_name='conteudo'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='lido',
            field=models.BooleanField(default=False, verbose_name='lido'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('ATRASO', 'Atraso'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='concluido'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='data de conclusao'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='data de fim'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='data de inicio'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='periodo',
            field=models.CharField(blank=True, choices=[('1_BIMESTRE', '1º bimestre'), ('2_BIMESTRE', '2º bimestre'), ('3_BIMESTRE', '3º bimestre'), ('4_BIMESTRE', '4º bimestre'), ('1_TRIMESTRE', '1º trimestre'), ('2_TRIMESTRE', '2º trimestre'), ('3_TRIMESTRE', '3º trimestre'), ('1_SEMESTRE', '1º semestre'), ('2_SEMESTRE', '2º semestre'), ('ANUAL', 'Anual')], max_length=20, null=True, verbose_name='periodo'),
        ),
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='tipo_periodo',
            field=models.CharField(blank=True, choices=[('BIMESTRE', 'Bimestre'), ('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('ANUAL', 'Anual')], max_length=20, null=True, verbose_name='tipo de periodo'),
        ),
        migrations.RunPython(migrar_conteudos_existentes, reverter_conteudos_existentes),
        migrations.AlterField(
            model_name='conteudoprogramatico',
            name='bimestre',
            field=models.PositiveSmallIntegerField(choices=[(1, '1º bimestre'), (2, '2º bimestre'), (3, '3º bimestre'), (4, '4º bimestre')], verbose_name='bimestre'),
        ),
        migrations.AlterField(
            model_name='conteudoprogramatico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluido'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20, verbose_name='status'),
        ),
    ]
