# Generated by Django 6.0.3 on 2026-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0005_alerta_conteudo_alerta_lido_alerta_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoprogramatico',
            name='bimestre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1º bimestre'), (2, '2º bimestre'), (3, '3º bimestre'), (4, '4º bimestre')], null=True, verbose_name='bimestre'),
        ),
    ]
