# Generated by Django 6.0.3 on 2026-05-24 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def vincular_disciplinas_existentes(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Turma = apps.get_model('planejamento', 'Turma')
    Disciplina = apps.get_model('planejamento', 'Disciplina')

    professor = User.objects.order_by('id').first()
    if not professor:
        return

    turma, _ = Turma.objects.get_or_create(
        professor=professor,
        nome='Turma legado',
        ano_letivo=timezone.localdate().year,
        defaults={
            'turno': 'MATUTINO',
            'descricao': 'Turma criada automaticamente para manter disciplinas existentes visiveis apos a migracao.',
        },
    )

    Disciplina.objects.filter(professor__isnull=True).update(professor=professor)
    Disciplina.objects.filter(turma__isnull=True).update(turma=turma)


def desvincular_disciplinas_existentes(apps, schema_editor):
    Disciplina = apps.get_model('planejamento', 'Disciplina')
    Disciplina.objects.update(professor=None, turma=None)


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0006_alter_conteudoprogramatico_bimestre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='professor'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('ano_letivo', models.PositiveIntegerField(verbose_name='ano letivo')),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20, verbose_name='turno')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-ano_letivo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='planejamento.turma', verbose_name='turma'),
        ),
        migrations.RunPython(vincular_disciplinas_existentes, desvincular_disciplinas_existentes),
    ]
