# Generated by Django 6.0.3 on 2026-05-24 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preencher_turmas_relacionadas(apps, schema_editor):
    Cronograma = apps.get_model('planejamento', 'Cronograma')
    Alerta = apps.get_model('planejamento', 'Alerta')

    for item in Cronograma.objects.select_related('disciplina__turma'):
        if item.disciplina_id and item.disciplina.turma_id and not item.turma_id:
            item.turma_id = item.disciplina.turma_id
            item.save(update_fields=['turma'])

    for alerta in Alerta.objects.select_related('conteudo__disciplina__turma'):
        if alerta.conteudo_id and alerta.conteudo.disciplina.turma_id and not alerta.turma_id:
            alerta.turma_id = alerta.conteudo.disciplina.turma_id
            alerta.save(update_fields=['turma'])


def limpar_turmas_relacionadas(apps, schema_editor):
    Cronograma = apps.get_model('planejamento', 'Cronograma')
    Alerta = apps.get_model('planejamento', 'Alerta')
    Cronograma.objects.update(turma=None)
    Alerta.objects.update(turma=None)


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0007_disciplina_professor_turma_disciplina_turma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='planejamento.turma', verbose_name='turma'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='planejamento.turma', verbose_name='turma'),
        ),
        migrations.CreateModel(
            name='AnotacaoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='titulo')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='planejamento.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Anotacao da turma',
                'verbose_name_plural': 'Anotacoes da turma',
                'ordering': ['-created_at', 'titulo'],
            },
        ),
        migrations.RunPython(preencher_turmas_relacionadas, limpar_turmas_relacionadas),
    ]
