# Generated by Django 6.0.3 on 2026-05-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0008_alerta_turma_cronograma_turma_anotacaoturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoprogramatico',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='atividades/', verbose_name='arquivo'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='atividades/', verbose_name='arquivo'),
        ),
    ]
