# Generated by Django 6.0.3 on 2026-05-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0009_conteudoprogramatico_arquivo_cronograma_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudoprogramatico',
            name='data_prevista',
        ),
        migrations.AlterField(
            model_name='conteudoprogramatico',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de conclusao'),
        ),
        migrations.DeleteModel(
            name='Cronograma',
        ),
    ]
