# Generated by Django 6.0.3 on 2026-05-25 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0011_alter_perfilusuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='matricula')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True, verbose_name='telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='planejamento.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoAvaliativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descricao')),
                ('tipo', models.CharField(choices=[('PROVA', 'Prova'), ('SEMINARIO', 'Seminario'), ('TRABALHO', 'Trabalho'), ('ATIVIDADE', 'Atividade em sala'), ('PARTICIPACAO', 'Participacao'), ('PROJETO', 'Projeto'), ('RECUPERACAO', 'Recuperacao'), ('OUTRO', 'Outro')], max_length=20, verbose_name='tipo')),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor maximo')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_avaliativos', to='planejamento.disciplina', verbose_name='disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_avaliativos', to='planejamento.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Processo avaliativo',
                'verbose_name_plural': 'Processos avaliativos',
                'ordering': ['-data', 'disciplina__nome', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='NotaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nota')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='planejamento.aluno', verbose_name='aluno')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='planejamento.processoavaliativo', verbose_name='processo avaliativo')),
            ],
            options={
                'verbose_name': 'Nota do aluno',
                'verbose_name_plural': 'Notas dos alunos',
                'ordering': ['aluno__nome', 'processo__titulo'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'processo'), name='nota_unica_por_aluno_processo')],
            },
        ),
    ]
