# Generated by Django 6.0.3 on 2026-05-25 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0012_aluno_processoavaliativo_notaaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='planejamento.disciplina', verbose_name='disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='planejamento.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Chamada',
                'verbose_name_plural': 'Chamadas',
                'ordering': ['-data', 'disciplina__nome'],
            },
        ),
        migrations.CreateModel(
            name='PresencaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True, verbose_name='presente')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observacao')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='planejamento.aluno', verbose_name='aluno')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='planejamento.chamada', verbose_name='chamada')),
            ],
            options={
                'verbose_name': 'Presenca do aluno',
                'verbose_name_plural': 'Presencas dos alunos',
                'ordering': ['aluno__nome'],
                'constraints': [models.UniqueConstraint(fields=('chamada', 'aluno'), name='presenca_unica_por_chamada_aluno')],
            },
        ),
    ]
