# Generated by Django 6.0.3 on 2026-05-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0013_chamada_presencaaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='periodo',
            field=models.CharField(blank=True, choices=[('1_BIMESTRE', '1º bimestre'), ('2_BIMESTRE', '2º bimestre'), ('3_BIMESTRE', '3º bimestre'), ('4_BIMESTRE', '4º bimestre'), ('1_TRIMESTRE', '1º trimestre'), ('2_TRIMESTRE', '2º trimestre'), ('3_TRIMESTRE', '3º trimestre'), ('1_SEMESTRE', '1º semestre'), ('2_SEMESTRE', '2º semestre'), ('ANUAL', 'Anual')], max_length=20, null=True, verbose_name='periodo'),
        ),
        migrations.AddField(
            model_name='chamada',
            name='tipo_periodo',
            field=models.CharField(blank=True, choices=[('BIMESTRE', 'Bimestre'), ('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('ANUAL', 'Anual')], max_length=20, null=True, verbose_name='tipo de periodo'),
        ),
        migrations.AddField(
            model_name='processoavaliativo',
            name='periodo',
            field=models.CharField(blank=True, choices=[('1_BIMESTRE', '1º bimestre'), ('2_BIMESTRE', '2º bimestre'), ('3_BIMESTRE', '3º bimestre'), ('4_BIMESTRE', '4º bimestre'), ('1_TRIMESTRE', '1º trimestre'), ('2_TRIMESTRE', '2º trimestre'), ('3_TRIMESTRE', '3º trimestre'), ('1_SEMESTRE', '1º semestre'), ('2_SEMESTRE', '2º semestre'), ('ANUAL', 'Anual')], max_length=20, null=True, verbose_name='periodo'),
        ),
        migrations.AddField(
            model_name='processoavaliativo',
            name='tipo_periodo',
            field=models.CharField(blank=True, choices=[('BIMESTRE', 'Bimestre'), ('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('ANUAL', 'Anual')], max_length=20, null=True, verbose_name='tipo de periodo'),
        ),
    ]
