# Generated by Django 6.0.3 on 2026-05-26 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0014_chamada_periodo_chamada_tipo_periodo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAlunoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_aulas', models.PositiveIntegerField(default=0, verbose_name='total de aulas')),
                ('total_faltas', models.PositiveIntegerField(default=0, verbose_name='total de faltas')),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota 1')),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota 2')),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota 3')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observacao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_turma', to='planejamento.aluno', verbose_name='aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_alunos', to='planejamento.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Registro do aluno na turma',
                'verbose_name_plural': 'Registros dos alunos nas turmas',
                'ordering': ['aluno__nome'],
                'constraints': [models.UniqueConstraint(fields=('turma', 'aluno'), name='registro_unico_por_aluno_turma')],
            },
        ),
    ]
