# Generated by Django 6.0.3 on 2026-05-26 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0015_registroalunoturma'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registroalunoturma',
            name='registro_unico_por_aluno_turma',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone',
        ),
        migrations.AddField(
            model_name='registroalunoturma',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_alunos', to='planejamento.disciplina', verbose_name='disciplina'),
        ),
        migrations.AddConstraint(
            model_name='registroalunoturma',
            constraint=models.UniqueConstraint(fields=('turma', 'aluno', 'disciplina'), name='registro_unico_por_aluno_turma_disciplina'),
        ),
    ]
