# Generated by Django 6.0.3 on 2026-05-26 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0016_remove_registroalunoturma_registro_unico_por_aluno_turma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencaaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_chamadas', to='planejamento.aluno', verbose_name='aluno'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da aula')),
                ('conteudo_aplicado', models.TextField(verbose_name='conteudo aplicado')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='planejamento.disciplina', verbose_name='disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='planejamento.turma', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['data', 'disciplina__nome'],
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True, verbose_name='presente')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observacao')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='planejamento.aluno', verbose_name='aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='planejamento.aula', verbose_name='aula')),
            ],
            options={
                'verbose_name': 'Presenca',
                'verbose_name_plural': 'Presencas',
                'ordering': ['aluno__nome'],
                'unique_together': {('aula', 'aluno')},
            },
        ),
    ]
