# Generated by Django 6.0.3 on 2026-05-26 02:11

from django.db import migrations, models


def preencher_quantidade_aulas(apps, schema_editor):
    Disciplina = apps.get_model('planejamento', 'Disciplina')
    for disciplina in Disciplina.objects.filter(quantidade_aulas=0):
        disciplina.quantidade_aulas = disciplina.carga_horaria
        disciplina.save(update_fields=['quantidade_aulas'])


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0017_alter_presencaaluno_aluno_aula_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='media_aprovacao',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=5, verbose_name='media de aprovacao'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='nota_total',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='nota total por periodo'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='quantidade_aulas',
            field=models.PositiveIntegerField(default=0, verbose_name='quantidade de aulas'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='tipo_periodo',
            field=models.CharField(choices=[('BIMESTRE', 'Bimestre'), ('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('ANUAL', 'Anual')], default='BIMESTRE', max_length=20, verbose_name='tipo de periodo'),
        ),
        migrations.RunPython(preencher_quantidade_aulas, migrations.RunPython.noop),
    ]
