# Generated by Django 6.0.3 on 2026-05-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0018_disciplina_media_aprovacao_disciplina_nota_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='quantidade_aulas',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade de aulas'),
        ),
    ]
