# Generated by Django 6.0.3 on 2026-05-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0019_aula_quantidade_aulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoavaliativo',
            name='tipo',
            field=models.CharField(choices=[('PROVA', 'Prova'), ('SEMINARIO', 'Seminario'), ('TRABALHO', 'Trabalho'), ('ATIVIDADE', 'Atividade em sala'), ('PARTICIPACAO', 'Participacao'), ('PROJETO', 'Projeto'), ('RECUPERACAO', 'Recuperacao'), ('PARALELA', 'Paralela'), ('OUTRO', 'Outro')], max_length=20, verbose_name='tipo'),
        ),
    ]
