# Generated by Django 6.0.3 on 2026-05-26 23:12

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('planejamento', '0020_alter_processoavaliativo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('planejamento.processoavaliativo',),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('planejamento.notaaluno',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='processoavaliativo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='atividades/', verbose_name='arquivo'),
        ),
        migrations.AddField(
            model_name='processoavaliativo',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='data de abertura'),
        ),
        migrations.AddField(
            model_name='processoavaliativo',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True, verbose_name='data de fechamento'),
        ),
        migrations.AddField(
            model_name='processoavaliativo',
            name='status',
            field=models.CharField(choices=[('A_REALIZAR', 'A realizar'), ('EM_ANDAMENTO', 'Em andamento'), ('CORRIGIDA', 'Corrigida'), ('FINALIZADA', 'Finalizada')], default='A_REALIZAR', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='processoavaliativo',
            name='tipo',
            field=models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('SEMINARIO', 'Seminario'), ('PRATICA', 'Atividade pratica'), ('EXERCICIO', 'Exercicio'), ('ATIVIDADE', 'Atividade em sala'), ('RECUPERACAO', 'Recuperacao'), ('PARALELA', 'Paralela'), ('PARTICIPACAO', 'Participacao'), ('PROJETO', 'Projeto'), ('OUTRO', 'Outro')], max_length=20, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=180, verbose_name='nome')),
                ('arquivo', models.FileField(upload_to='academico/', verbose_name='arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='planejamento.processoavaliativo', verbose_name='atividade')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='planejamento.aula', verbose_name='aula')),
                ('conteudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_extras', to='planejamento.conteudoprogramatico', verbose_name='conteudo')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['-created_at', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BIMESTRE', 'Bimestre'), ('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('ANUAL', 'Anual')], max_length=20, verbose_name='tipo')),
                ('codigo', models.CharField(choices=[('1_BIMESTRE', '1º bimestre'), ('2_BIMESTRE', '2º bimestre'), ('3_BIMESTRE', '3º bimestre'), ('4_BIMESTRE', '4º bimestre'), ('1_TRIMESTRE', '1º trimestre'), ('2_TRIMESTRE', '2º trimestre'), ('3_TRIMESTRE', '3º trimestre'), ('1_SEMESTRE', '1º semestre'), ('2_SEMESTRE', '2º semestre'), ('ANUAL', 'Anual')], max_length=20, verbose_name='codigo')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_letivos', to='planejamento.disciplina', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'Periodo letivo',
                'verbose_name_plural': 'Periodos letivos',
                'ordering': ['disciplina__nome', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('disciplina', 'codigo'), name='periodo_unico_por_disciplina')],
            },
        ),
        migrations.CreateModel(
            name='Recuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1_BIMESTRE', '1º bimestre'), ('2_BIMESTRE', '2º bimestre'), ('3_BIMESTRE', '3º bimestre'), ('4_BIMESTRE', '4º bimestre'), ('1_TRIMESTRE', '1º trimestre'), ('2_TRIMESTRE', '2º trimestre'), ('3_TRIMESTRE', '3º trimestre'), ('1_SEMESTRE', '1º semestre'), ('2_SEMESTRE', '2º semestre'), ('ANUAL', 'Anual')], default='ANUAL', max_length=20, verbose_name='periodo')),
                ('nota_recuperacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota de recuperacao')),
                ('nota_paralela', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota paralela')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observacao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacoes', to='planejamento.aluno', verbose_name='aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacoes', to='planejamento.disciplina', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'Recuperacao',
                'verbose_name_plural': 'Recuperacoes',
                'ordering': ['aluno__nome', 'disciplina__nome', 'periodo'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'disciplina', 'periodo'), name='recuperacao_unica_por_aluno_disciplina_periodo')],
            },
        ),
    ]
