# Generated by Django 6.0.3 on 2026-05-26 23:32

from django.db import migrations, models


TIPOS_LEGADOS = {
    'PROVA': 'Prova escrita',
    'TRABALHO': 'Trabalho em grupo',
    'SEMINARIO': 'Seminario',
    'PRATICA': 'Atividade pratica',
    'EXERCICIO': 'Exercicio avaliativo',
    'ATIVIDADE': 'Atividade em sala',
    'RECUPERACAO': 'Recuperacao',
    'PARALELA': 'Paralela',
    'PARTICIPACAO': 'Participacao',
    'PROJETO': 'Projeto',
    'OUTRO': 'Outro',
}


def converter_tipos_legados(apps, schema_editor):
    ProcessoAvaliativo = apps.get_model('planejamento', 'ProcessoAvaliativo')
    for codigo, nome in TIPOS_LEGADOS.items():
        ProcessoAvaliativo.objects.filter(tipo=codigo).update(tipo=nome)


class Migration(migrations.Migration):

    dependencies = [
        ('planejamento', '0022_criar_periodos_letivos_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoavaliativo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='observacao'),
        ),
        migrations.AlterField(
            model_name='processoavaliativo',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='conteudo aplicado'),
        ),
        migrations.AlterField(
            model_name='processoavaliativo',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='tipo'),
        ),
        migrations.RunPython(converter_tipos_legados, migrations.RunPython.noop),
    ]
